description: "Stack test environment to practice rules on RouterOS"
name: stack-routeros
display-name: "Stack RouterOS"
picture: stack.png
category: "Backend"
compatibility: ["Docker", "Unix", "RouterOS"]
technologies: ["Docker", "API"]
about: docs/about.md
use-cases:
  - title: "Default"
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml