description: "Stack test environment to practice rules on RouterOS"
name: stack-routeros
display-name: "Stack RouterOS"
picture: stack.png
category: "Backend"
compatibility:
  - "Java"
technologies:
  - "Java"
about: docs/about.md
use-cases:
  - title: "Default"
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml